// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iobruecevpysktdkcmlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvYnJ1ZWNldnB5c2t0ZGtjbWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTY0MzMsImV4cCI6MjA2NTI3MjQzM30.gRPZyVkVWLX16tPETL7Fzm3RuDGF-QkhCoftjVALxbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);